"""Generate C constants from the validated shared protocol definition."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any

try:
    from .shared_config import layout_details, load_and_validate
except ImportError:
    from shared_config import layout_details, load_and_validate


def macro_name(value: str) -> str:
    return re.sub(r"[^A-Z0-9]+", "_", value.upper()).strip("_")


def c_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def integer_units(milliseconds: int, numerator: int, denominator: int, name: str) -> int:
    scaled = milliseconds * numerator
    if scaled % denominator:
        raise ValueError(f"{name}={milliseconds} ms cannot be represented exactly")
    return scaled // denominator


def validate_pairing_passkey(pairing_passkey: str) -> None:
    if re.fullmatch(r"[0-9]{6}", pairing_passkey) is None:
        raise ValueError("pairing passkey must contain exactly six digits")


def generate_header(
    config: dict[str, Any], source_name: str, pairing_passkey: str
) -> str:
    validate_pairing_passkey(pairing_passkey)
    bluetooth = config["bluetooth"]
    device = config["device"]
    simulation = config["simulation"]
    authentication = config["authentication"]
    protocol = config["protocol"]
    layouts = protocol["layouts"]

    lines = [
        "#pragma once",
        "",
        f"/* Generated from {source_name}. Do not edit this file directly. */",
        "",
        f"#define THERMOMETER_BLE_DEVICE_NAME_PREFIX {c_string(bluetooth['device_name_prefix'])}",
        f"#define THERMOMETER_BLE_SERVICE_UUID {c_string(bluetooth['service_uuid'])}",
        f"#define THERMOMETER_BLE_REQUEST_UUID {c_string(bluetooth['request_characteristic_uuid'])}",
        f"#define THERMOMETER_BLE_RESPONSE_UUID {c_string(bluetooth['response_characteristic_uuid'])}",
        f"#define THERMOMETER_BLE_PAIRING_PASSKEY {int(pairing_passkey)}U",
        f"#define THERMOMETER_BLE_PAIRING_PASSKEY_TEXT {c_string(pairing_passkey)}",
        f"#define THERMOMETER_BLE_PREFERRED_ATT_MTU {bluetooth['preferred_att_mtu']}U",
    ]

    advertising = bluetooth["advertising_interval_ms"]
    connection = bluetooth["preferred_connection"]
    lines.extend(
        [
            f"#define THERMOMETER_BLE_ADV_INTERVAL_MIN_UNITS {integer_units(advertising['minimum'], 8, 5, 'advertising minimum')}U",
            f"#define THERMOMETER_BLE_ADV_INTERVAL_MAX_UNITS {integer_units(advertising['maximum'], 8, 5, 'advertising maximum')}U",
            f"#define THERMOMETER_BLE_CONN_INTERVAL_MIN_UNITS {integer_units(connection['minimum_interval_ms'], 4, 5, 'connection minimum')}U",
            f"#define THERMOMETER_BLE_CONN_INTERVAL_MAX_UNITS {integer_units(connection['maximum_interval_ms'], 4, 5, 'connection maximum')}U",
            f"#define THERMOMETER_BLE_PERIPHERAL_LATENCY {connection['peripheral_latency']}U",
            f"#define THERMOMETER_BLE_SUPERVISION_TIMEOUT_UNITS {integer_units(connection['supervision_timeout_ms'], 1, 10, 'supervision timeout')}U",
            "",
            f"#define THERMOMETER_SENSOR_COUNT {device['sensor_count']}U",
            f"#define THERMOMETER_HISTORY_CAPACITY {device['history_capacity_records']}U",
            f"#define THERMOMETER_SAMPLE_PERIOD_MS {device['sample_period_ms']}U",
            f"#define THERMOMETER_SAMPLING_TASK_STACK_BYTES {device['sampling_task_stack_bytes']}U",
            f"#define THERMOMETER_SAMPLING_TASK_PRIORITY {device['sampling_task_priority']}U",
            f"#define THERMOMETER_FAILED_READ_LIMIT {device['failed_reads_before_disconnected']}U",
            f"#define THERMOMETER_SUCCESSFUL_READ_LIMIT {device['successful_reads_before_reconnected']}U",
            f"#define THERMOMETER_DEFAULT_BACKLIGHT_PERCENT {device['default_backlight_percent']}U",
            "",
            f"#define THERMOMETER_FAKE_DISCONNECTS {1 if simulation['simulate_disconnects'] else 0}U",
            f"#define THERMOMETER_FAKE_DISCONNECT_CYCLE_SAMPLES {simulation['disconnect_cycle_samples']}U",
        ]
    )
    for index, sensor in enumerate(simulation["sensors"], start=1):
        prefix = f"THERMOMETER_FAKE_SENSOR_{index}"
        for key, value in sensor.items():
            lines.append(f"#define {prefix}_{macro_name(key)} {value}")

    lines.extend(
        [
            "",
            f"#define THERMOMETER_AUTH_DOMAIN {c_string(authentication['domain_separator'])}",
            f"#define THERMOMETER_AUTH_NONCE_SIZE {authentication['nonce_size_bytes']}U",
            f"#define THERMOMETER_AUTH_PROOF_SIZE {authentication['proof_size_bytes']}U",
            f"#define THERMOMETER_AUTH_CHALLENGE_TIMEOUT_MS {int(authentication['challenge_timeout_seconds'] * 1000)}U",
            f"#define THERMOMETER_AUTH_MAX_FAILURES {authentication['maximum_failures']}U",
            f"#define THERMOMETER_AUTH_LOCKOUT_MS {int(authentication['lockout_seconds'] * 1000)}U",
            "",
            f"#define THERMOMETER_PROTOCOL_VERSION {protocol['version']}U",
            f"#define PROTOCOL_RESPONSE_FLAG {protocol['response_flag']}U",
            f"#define PROTOCOL_MAX_HISTORY_RECORDS {protocol['max_history_records_per_chunk']}U",
        ]
    )
    for group_name, prefix in (
        ("opcodes", "PROTOCOL_OPCODE_VALUE"),
        ("status_codes", "PROTOCOL_STATUS_VALUE"),
        ("visible_states", "PROTOCOL_VISIBLE_STATE_VALUE"),
        ("data_statuses", "PROTOCOL_DATA_STATUS_VALUE"),
    ):
        for name, value in protocol[group_name].items():
            lines.append(f"#define {prefix}_{macro_name(name)} {value}U")

    for layout_name, layout in layouts.items():
        size, offsets = layout_details(layout)
        prefix = f"PROTOCOL_{macro_name(layout_name)}"
        lines.extend(("", f"#define {prefix}_SIZE {size}U"))
        for field_name, offset in offsets.items():
            lines.append(
                f"#define {prefix}_{macro_name(field_name)}_OFFSET {offset}U"
            )

    header_size, _ = layout_details(layouts["header"])
    prefix_size, _ = layout_details(layouts["history_chunk_prefix"])
    record_size, _ = layout_details(layouts["history_record"])
    maximum_packet_size = (
        header_size
        + prefix_size
        + protocol["max_history_records_per_chunk"] * record_size
    )
    lines.extend(("", f"#define PROTOCOL_MAX_PACKET_SIZE {maximum_packet_size}U", ""))
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--pairing-passkey", required=True)
    args = parser.parse_args()

    config = load_and_validate(args.input)
    header = generate_header(config, args.input.name, args.pairing_passkey)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(header, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
